### ISSUE TITLE
v1.0.3 errors in trace - request headers missing

### ISSUE THREAD

**Issue by jschutte27** [Axway-API-Management-Plus/dynatrace-apim-oneagent#10]
Hi @rathnapandi,

In Issue #7 you fixed the problem with services not showing up in dynatrace, but I am still seeing the errors in the api gateway trace.  This doesn't appear to be serious as I see the same data as on v1.0.1 in our production environment.  

Every request shows errors like this in api gateway:
FATAL	4/17/23, 07:45:03.600	DynatraceModule :[75696d6e] can't set fieldname 'requestHeader': must be done before node is being started.
INFO	4/17/23, 07:45:03.600	                                Dynatrace :: outgoing x-dynatrace header FW4;-4620968c8991c29f777e55a794257110;7hcdd19af4f30a68b2
FATAL	4/17/23, 07:45:03.600	                                DynatraceModule :[84a097] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL	4/17/23, 07:45:03.600	                                DynatraceModule :[84a097] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL	4/17/23, 07:45:03.600	                                DynatraceModule :[84a097] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL	4/17/23, 07:45:03.600	                                DynatraceModule :[84a097] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL	4/17/23, 07:45:03.600	                                DynatraceModule :[84a097] can't set fieldname 'requestHeader': must be done before node is being started.

I noticed we only get the "Trace ID" and "Span ID" request headers in dynatrace (v1.0.1 and v1.0.3) so I wonder if this is related.

Thanks,
Jeremiah

**Comment by rathnapandi** [comment]
Hi Jeremiah, 

The error is coming from Dynatrace, the initial version wed did not implement Dynatrace loggingcallback (https://github.com/Dynatrace/OneAgent-SDK-for-Java#troubleshooting). it was added recently and it printes the above errores. 
 Can you check with Dynatrace support team? based on their feedback we can fix if needed.

**Comment by jschutte27** [comment]
We have the code in #11 running in our dev environment and it seems to be working ok and fixes the Fatal errors.  Request headers still are not all coming through though.

**Comment by rathnapandi** [comment]
Thanks @jschutte27, I will merge pull request.  Can you share some details on what is missing on request headers?

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

I have updated the code under the branch https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/issue10. could you please test it?

**Comment by jschutte27** [comment]
Hi @rathnapandi,

The headers are inconsistently coming into Dynatrace.  It feels like Dynatrace might be filtering them somewhere.  I see the Accept and Authorization header, but not Content-Type, Content-Length, Host, User-Agent, ect.  I have Authorization and KeyId redacted in Axway api gateway, but this seems to pick it up anyway.  I can mask the data in dynatrace, but it might be nicer to filter those header out in this module so they are not sent.

The headers are not a critical feature for us so I would be fine leaving it as is, but would like to filter out the sensitive ones.

I will try your updates shortly.  Did you see my note about the info trace messages?

Thanks,
Jeremiah

**Comment by jschutte27** [comment]
I tried the issue 10 branch and it reverted the change that removed the header errors so I get this in the trace:
DEBUG	4/27/23, 11:07:30.135	Dynatrace :: Starting around consumer
DEBUG	4/27/23, 11:07:30.135	Dynatrace :: Consumer Headers before proceed: {Host=[devwebapi.xxx.com], User-Agent=[Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17763.3770], X-Forwarded-For=[xx]}
INFO	4/27/23, 11:07:30.135	DynatraceModule :[6dabb282] can't set fieldname 'requestHeader': must be done before node is being started.
INFO	4/27/23, 11:07:30.135	DynatraceModule :[6dabb282] can't set fieldname 'requestHeader': must be done before node is being started.
INFO	4/27/23, 11:07:30.135	DynatraceModule :[6dabb282] can't set fieldname 'requestHeader': must be done before node is being started.

The addOutgoingHeaders call has to be before outgoingWebRequestTracer.start(); based on thy dynatrace documentation.  
https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/blob/75ff612954c8bf56336249990f9cde36d03e880f/src/main/java/com/axway/oneagent/utils/OneAgentSDKUtils.java#L65
That made the errors go away and it was adding some headers, but not all with it that way.  Now with the errors we are not seeing any headers come through to dynatrace.

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

Thank you for validating, i have added a log message on info level to print app id and name.  Removed other log messages to avoid IO operations. 

Also, adding all header additions before outgoingWebRequestTracer.start() method.   Please validate it once you test i will merge to main branch.

**Comment by jschutte27** [comment]
Thanks for the log entry.  Could you add a space some delimitor between the values?
INFO	4/27/23, 13:07:56.382	Dynatrace :: Application Id :6617bb2d-3580-xxxx-b98c-e60bb7ee6af7Application Name :testapp-dev

I am getting this error now:
DEBUG	4/27/23, 13:18:12.354	Dynatrace :: Starting around consumer
DEBUG	4/27/23, 13:18:12.354	Dynatrace :: Consumer Headers before proceed: {redacted}
INFO	4/27/23, 13:07:56.382	Dynatrace :: Application Id :6617bb2d-3580-xxxx-b98c-e60bb7ee6af7Application Name :testapp-dev
ERROR	4/27/23, 13:07:56.382	DynatraceModule :custom request attribute failed: not on path
ERROR	4/27/23, 13:07:56.382	DynatraceModule :custom request attribute failed: not on path
ERROR	4/27/23, 13:07:56.382	DynatraceModule :custom request attribute failed: not on path
ERROR	4/27/23, 13:07:56.382	DynatraceModule :custom request attribute failed: not on path

I'm guessing it is because addRequestAttributes(appName, orgName, appId, null); is before outgoingWebRequestTracer.start();.  I'll test that out and see what happens.

I do see all the headers in dynatrace now though:
Accept	[application/json]
Cdn-Loop	[cloudflare; subreqs=1]
Cf-Connecting-Ip	[xx.1xx.120.70]
Cf-Ew-Via	[15]
Cf-Ipcountry	[US]
Cf-Origin-Https	[on]
Cf-Ray	[7be90ef3c4eeeae9-DFW]
Cf-Visitor	[{"scheme":"https"}]

They are all in arrays which isn't serious, but would look nicer if it was a simple string.

Would it make sense to add a list of header names to exclude that is configurable in the jvm.xml file?

**Comment by jschutte27** [comment]
I moved the addRequestAttributes call after each of the start() calls locally and it fixed the attributes and removed the errors.

**Comment by rathnapandi** [comment]
Thanks @jschutte27 , 

Added space and delimiter for logs and moved addRequestAttributes after start(), can you review the code base and confirm?

**Comment by rathnapandi** [comment]
I will add the feature to exclude http headers.  https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/issues/13

**Comment by jschutte27** [comment]
I have this new version running and so far it seems good.  Would it work to try convert the header values to string so they don't have the brackets in dynatrace?

**Comment by rathnapandi** [comment]
Done.

**Comment by jschutte27** [comment]
The headers look good.  Thanks!

I noticed that the x-dynatrace header on outgoing requests was empty and that the outgoingTag was empty.  This was causing the backend request not to be linked to the axway request in dynatrace.  I reordered the requests and it looks like this works correctly:
```
try {
            addOutgoingHeaders(outgoingWebRequestTracer, headers);
            outgoingWebRequestTracer.start();
            String outgoingTag = outgoingWebRequestTracer.getDynatraceStringTag();
            Trace.debug("Dynatrace :: outgoing x-dynatrace header " + outgoingTag);
            if (headers != null) {
                headers.setHeader(OneAgentSDK.DYNATRACE_HTTP_HEADERNAME, outgoingTag);
            }
            addRequestAttributes(appName, orgName, appId, null);
            Trace.debug("Dynatrace :: Get Message Attributes");
            getAttributes(message);
            pjp.proceed();
}
```

**Comment by rathnapandi** [comment]
Done, can you please do the final validation?

**Comment by jschutte27** [comment]
I believe this looks good.  Thanks a lot!

**Comment by rathnapandi** [comment]
@jschutte27 
Merged the changes to master
