### ISSUE TITLE
update branch "apim-Aug-2022"

### ISSUE THREAD

**Issue by PieCol75** [Axway-API-Management-Plus/dynatrace-apim-oneagent#16]
It's possible update the branch "apim-Aug-2022" with the last fixes ? 
In particular for to be able to extract the Custom Attributes. 
Or to extend the test for the main branch with the APIM November 2021 release ?

**Comment by rathnapandi** [comment]
Hi @PieCol75, 
I can merge the changes; would it be possible to test it?

**Comment by PieCol75** [comment]
Hi @rathnapandi 
thanks for the response. Yes we can test it.
I want to explain you that:
-we use APIM November 2021 release
-we test succesfully the branch "apim-Aug-2022", but it not include the possibility to extract the CustomAttributes
-we try to use the main branch but it don't run correctly because in Dynatrace side it don't recognize the services but show only a generic "Requests executed in background threads of <APIM_INSTANCE_NAME>"

**Comment by rathnapandi** [comment]
Hi @PieCol75, 

Could you please use the branch  https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/captureconecttourlinokepolicy for your testing.  It works with November 2021 and latest release. Also it fixes issue #17

**Comment by PieCol75** [comment]
Hi @rathnapandi ,
we have testing your release. We found that it appears not to create service for each API in api manager (like in the previous release).
All he traffic in dynatrace shows under the "Requests executed in background threads of vshell" .
Before: "Service_API_1", "Service_API_2", "Service_API_3",.....
After: "Requests executed in background threads of <PROCESS_NAME of vshell"

Seem to be the same issue #7.

Our lib versions:
Mar 22 10:37 aspectjweaver-1.9.6.jar
Mar 22 10:37 oneagent-sdk-1.8.0.jar
May 15 10:16 dynatrace-aspectj-1.0.4.jar

Thanks

**Comment by PieCol75** [comment]
Hi @rathnapandi,
in previous message we have used the not correct branch (main). Now we are using the correct branch (https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/captureconecttourlinokepolicy), and test it. Now our  libs are:
Mar 22 10:37 aspectjweaver-1.9.6.jar
Mar 22 10:37 oneagent-sdk-1.8.0.jar
May 16 09:45 dynatrace-aspectj-1.0.6-2.jar

But the service name on Dynatrace have the same issue (All he traffic in dynatrace shows under the "Requests executed in background threads of vshell").
Thanks

**Comment by rathnapandi** [comment]
Hi @PieCol75 , 

The code deployed and tested recently without any issues. Can you share your jvm.xml file?

**Comment by PieCol75** [comment]
Hi @rathnapandi ,
our jvm.xml file:

<ConfigurationFragment>
    <VMArg name="-javaagent:/axway/Axway-7.7.0/apigateway/ext/lib/aspectjweaver-1.9.6.jar"/>
</ConfigurationFragment>
<img width="570" alt="jvm_xml" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/2f3e2fc2-576e-4fc1-8faf-8992f9a8404e">

With the old versione (branch apim-Aug-2022) creates service for each API in ApiManager:
<img width="333" alt="Before_1" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/07bccd65-63c0-4bc9-ab1c-501789f59c57">
<img width="319" alt="Before_2" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/fafb3dc3-bd3c-426e-bb57-caf3cda78ffd">

With the new version branch (https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/captureconecttourlinokepolicy) only creates service for built in API Manager:

<img width="361" alt="After (2)" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/fede1095-1972-45fe-80e5-f3a8fa88f14d">



Thanks

**Comment by rathnapandi** [comment]
Hi @PieCol75, 

Can you list file names under apigateway/ext/lib folder and apigateway/groups/group-x/instance-x/ext/lib. 

Also, add some debug statement under https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/blob/main/src/main/java/com/axway/aspects/apim/AxwayAspect.java?plain=1#L68 to see it is hitting that part of code.

**Comment by PieCol75** [comment]
Hi @rathnapandi ,
the list under apigateway/ext/lib folder:

<img width="593" alt="SystemExtLib" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/1613e8c9-897e-4553-bc3c-ce578e5dda33">
 and the list under apigateway/groups/group-x/instance-x/ext/lib :
<img width="620" alt="GroupExtLib" src="https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/132379785/f72e10f4-9f37-436c-99de-18e969669d32">

I attach also the output log of the start instance 
[err.log](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/11540741/err.log)

I've tried (i'm not a dev) to chenge the Aspect.java, addin debug statement (line 15,73,79), but I don't view any logs in trace file about the debug.
[AxwayAspect.java.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/11540759/AxwayAspect.java.txt)

I want to explicit that with:
branch Aug2022 (dynatrace-aspectj-1.0.2.jar) view of service in Dynatrace is OK
branch "main" (dynatrace-aspectj-1.0.4.jar) view of service in Dynatrace is KO (all under "Requests executed in background threads of vshell")
branch "captureconecttourlinokepolicy" (dynatrace-aspectj-1.0.6-2.jar) view of service in Dynatrace is KO (all under "Requests executed in background threads of vshell")

We use ApiGw version 7.7 November 2021

Thanks

**Comment by rathnapandi** [comment]
Hi @PieCol75 , 

Fix to support November 2021 release available on - https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/Nov2021

Please test it.

**Comment by PieCol75** [comment]
Hi @rathnapandi ,
i  confirm you that we are using the release https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/Nov2021 and that it fixed the issue.
Thanks !
