### ISSUE TITLE
Missing Tracing of policies exposed on path?

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/dynatrace-apim-oneagent#20]
hi @rathnapandi,

I want to report you the following behaviour.

consider the following end 2 end call.

API MANAGER FRONTEND API -> API MANAGER (his own gateway listener) -> API MANAGER (oauth listener) -> other orchestrated services.

In the Dynatrace distributed traces I see that at the oauth listener point the trace is interrupted and I cannot see further.

Is this a known problem? 
does simple policies exposed on a path (not WebServices or REST API) are tracked with this aspect classes?

thanks

**Comment by gcornacchia** [comment]
here i what I see

![image_2023_06_15T14_35_15_452Z-edit](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/15086835/ead593fa-bbf0-425d-96fb-c22bf436d04c)

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

Simple policy will be tracked if we don't have API manager.  For example, If API manager is running as separate process and API Gateway Oauth server is running as separate process then we can see end to end view on Dynatrace. 

Sample config without API manager. 

```xml
<ConfigurationFragment>
    <VMArg name="-javaagent:/home/axway/Axway-7.7.0-Aug2021/apigateway/ext/lib/aspectjweaver-1.9.6.jar"/>
    <SystemProperty name="apimanager" value="false" />
</ConfigurationFragment>
```

Your scenario won't work (API manager and oauth server are running as same process with different listeners), it is a limitation with current implementation.  

Thanks
Rathna
