### ISSUE TITLE
Changing behaviour in handling timeout errors 

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/dynatrace-apim-oneagent#21]
Hi,
We've found a strange behavior in handling timeout errors in a gateway policy calling a backend endpoint.
Consider the following versions:

Axway API Gateway version: 7.7 nov 2021
Dynatrace-apim-oneagent version: branch Nov2021

With Dynatrace agent on:

![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/15086835/044308dc-982f-4ba9-b2ad-c786a61c5e67)

The connect to URL exits with a false value

![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/15086835/88735b93-4253-4292-bd09-ba1244999dc4)

The same package, In another environment without Dynatrace agent:

![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/15086835/22a29e4f-9fa6-4b95-966b-2d8e344e8362)

After the connect to url the fault handler is invoked. 

![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/15086835/d115000a-84c9-47c1-adf9-d0aacd1f43be)

So it seems that dynatrace-apim-oneagent is changing the behavior by changing the exception and changing the policy flow.

What do you think?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

I made changes to handle the exception. Can you checkout the latest code from Nov 2021 branch and test it?

**Comment by gcornacchia** [comment]
hi @rathnapandi,
our tests with patched libraries gave us a positive outcome. 

Thanks

**Comment by gcornacchia** [comment]
hi @rathnapandi just a question about the lifecycle of this component, I don't see tags or released packages, moreover there are different branches for compatibility with different Axway versions. 
This patch you just made is it already merged into the main branch? 
I'm thinking that "tomorrow" when we update to a newer API gateway version we need also to update also these libraries....

**Comment by rathnapandi** [comment]
Hi @gcornacchia,
We are creating a branch whenever there is incompatibility with old api gateway libraries.  We can introduce tags and no plans to do release as it uses API gateway internal libraries which blocks creating CI / CD pipeline. 

I am waiting for your response to merge the changes to the main branch.  will do it shortly. 

Thanks
Rathna

**Comment by rathnapandi** [comment]
Changes merged with main branch. 

Thanks
Rathna
