### ISSUE TITLE
Name of Services defined in API Gateway

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/dynatrace-apim-oneagent#22]
Looking in Dynatrace we've found that for API Manager apis all the informations are extracted correctely.
For API defined in API Gateway (both REST or SOAP), we see the name with the value of the first segment of request uri.

For example:
/test/myservice/v1 

Dynatrace service name -> test 

Given that we use a common prefix for all API endpoints this is not so clear.

Is it possible to extract the entire service name defined in API Gateway (as defined in REST API Repository or WebService Repository) or the entire base path?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

We can extract service name if available if not we use the existing flow.

**Comment by gcornacchia** [comment]
Hi @rathnapandi , if you provide us with a patch (always in Nov2021 branch) we can do some tests

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

Th fix is available in Nov2021 branch, please test and share your results.

**Comment by gcornacchia** [comment]
HI @rathnapandi, I don't think it's working.

here are the logs files of an API call, the service name is extracted as **co001** instead of the desired  **MyService_v1**

Maybe it's because the "Set Web Service Context" is executed after dynatrace aspect method

DEBUG	9/22/23, 16:22:47.778	Adding MessageListener: com.vordel.dwe.TrafficMonitorMessageListener@20e41916
INFO	9/22/23, 16:22:47.778	Service Name : co001
DEBUG	9/22/23, 16:22:47.778	Dynatrace :: Starting around consumer
DEBUG	9/22/23, 16:22:47.778	Dynatrace :: Consumer Headers before proceed: {Accept=[text/xml, multipart/related], Host=[localhost-per-be:38080], SOAPAction=[""], User-Agent=[JAX-WS RI 2.3.3 git-revision#b4c5bb6], Via=[1.0 node1 (), 1.0 node1 (), 1.0 node1 ()], X-dynaTrace=[]}
DEBUG	9/22/23, 16:22:47.778	Dynatrace :: X-Dynatrace-Header
DEBUG	9/22/23, 16:22:47.778	Circuit reference [Global Request Policy] valid and enabled - calling
DEBUG	9/22/23, 16:22:47.778	Circuit reference [Custom Request Policy] is not enabled - ignoring
DEBUG	9/22/23, 16:22:47.778	Circuit reference [Path Specific Policy] valid and enabled - calling
DEBUG	9/22/23, 16:22:47.778	run circuit "CO001_MyService_v1_switch"...
DEBUG	9/22/23, 16:22:47.778	run filter [Set Web Service Context] {
DEBUG	9/22/23, 16:22:47.778	        Set the service name to be MyService_v1
DEBUG	9/22/23, 16:22:47.778	        Adding MessageListener: com.vordel.circuit.ws.ServiceContextProcessor$SCPMessageListener@2fe9506f
DEBUG	9/22/23, 16:22:47.778	        Setting webservice context
DEBUG	9/22/23, 16:22:47.778	        Set the Web Service context to be MyService_v1
DEBUG	9/22/23, 16:22:47.778	} = 1, filter [Set Web Service Context]

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

How did you set up the API? The service.name comes from Set Web Service Context or Set Service Context filter.  Not sure where the value co001 set. Also, can you pull the latest code?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

Looks like service.name is not available during the execution of dynatrace aspect. Let me check and get back to you.

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

Looks like service.name is not available during the exuecton of dynatrace aspect .

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 
Changed the dynatrace aspject to capture service.name, please pull the latest code.

**Comment by rathnapandi** [comment]
Added a service name a request attribute as service.name attribute  is not available when the request hits gateway. 

Please reopen the issue if you see any issue
