### ISSUE TITLE
FYI: Dynatrace is grouping services as volatile WebRequest 

### ISSUE THREAD

**Issue by avinashpodisetti** [Axway-API-Management-Plus/dynatrace-apim-oneagent#23]
as on Axway SDK, we are dividing the services by URI, specifically on front-end axway servers, Dynatrace is grouping services as volatile webrequests. 

https://community.dynatrace.com/t5/Open-Q-A/volatile-WebRequest/td-p/180705

to resolve this issue,  increasing the bucket size of dynatrace managed environment via support ticket.

**Comment by rathnapandi** [comment]
Thanks @avinashpodisetti, I will add this to read me.
