### ISSUE TITLE
API Gateway 7.7 20230530 version integration exception

### ISSUE THREAD

**Issue by WangLucy123** [Axway-API-Management-Plus/dynatrace-apim-oneagent#25]
We integrate with Dynatrace in API Gateway7.7 20230530 version. After restarting the service, all API calls will be displayed in the Block of API Gateway Manager8090, and the api calls cannot be monitored in Dynatrace.
Step 1: Add aspectjweaver-1.9.6.jar, AxwayAspectJ-1.0.jar and oneagent-sdk-1.8.0.jar to INSTALL_DIR/apigateway/ext/lib.
Step 2: Created jvm.xml under INSTALL_DIR/apigateway/conf.
```
<ConfigurationFragment>
     <VMArg name="-javaagent:/data/axway/Axway-7.7.0/apigateway/ext/lib/aspectjweaver-1.9.6.jar"/>
</ConfigurationFragment>
```
Step 3: Restart service.

Has version API Gateway7.7 20230530 been integrated with Dynatrace? Is there a solution to this problem?

**Comment by rathnapandi** [comment]
Hi @WangLucy123, 

I tested it against API Gateway7.7 20230530 version using github branch - https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/tree/issue22. 

Can you please remove AxwayAspectJ-1.0.jar, download  
[axwaydynatrace.tar.gz](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/12742611/axwaydynatrace.tar.gz),  extract to apigateway/ext/lib and test it. 

Also, can you share screenshot and traces too?

**Comment by WangLucy123** [comment]
Dear all,

I have deleted AxwayAspectJ-1.0.jar and downloaded GitHub branch issue22 to the server, but executing gradlew clean jar failed because the server cannot access https://services.gradle.org/distributions/gradle-6.7-bin.zip.
***@***.***

Best Regards
Lucy

**Comment by WangLucy123** [comment]
Wang Lucy, ***@***.***) would like to recall the message, "[Axway-API-Management-Plus/dynatrace-apim-oneagent] API Gateway 7.7 20230530 version integration exception (Issue #25)".

**Comment by WangLucy123** [comment]
Dears,

I have unzipped axwaydynatrace.tar.gz to the INSTALLDIR/apigateway/ext/lib directory, and configured the jvm.xml file under INSTALLDIR/apigateway/conf.
***@***.***
***@***.***

It is wrong to call the interface response body, this happens for all calls.
wrong result:
***@***.***
correct result:
***@***.***

Best Regards
Lucy

**Comment by rathnapandi** [comment]
Hi @WangLucy123 , 

Looks like the logs are obfuscated. Can you reshare it?

**Comment by WangLucy123** [comment]
Hi rathnapandi,

I have unzipped axwaydynatrace.tar.gz to the INSTALLDIR/apigateway/ext/lib directory, and configured the jvm.xml file under INSTALLDIR/apigateway/conf.
![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/146203390/91384e42-b503-4f32-876d-68378dfcc52d)
![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/146203390/268789cc-ae0b-4d11-9bff-9c665b28c8e0)

It is wrong to call the interface response body, this happens for all calls.
wrong result:
![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/146203390/c11a48ea-8e88-42b5-affe-930082b52416)

correct result:
![image](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/assets/146203390/85701986-ed70-471c-aa6c-c073569e4d49)

**Comment by WangLucy123** [comment]
Hi @ rathnapandi<https://github.com/rathnapandi> ,

How are you?

Is there any progress now on this problem we encountered? Is there any way to solve this problem? Looking forward to your reply, thank you very much.

**Comment by rathnapandi** [comment]
Hi @WangLucy123, 

I can't reproduce the issue with same library which is used for testing , can you enable DEBUG log level and share the logs?

Thanks
Rathna

**Comment by WangLucy123** [comment]
Hi @rathnapandi,
At present, we have found the cause of the problem, which comes from our OS image problem. Thank you for your support.

Best Regards
Lucy

**Comment by WangLucy123** [comment]
Hi @rathnapandi,
At present, we have found the cause of the problem, which comes from our OS image problem. Thank you for your support.

Best Regards
Lucy
