### ISSUE TITLE
7.7.Aug2023 and Java 11 testing?

### ISSUE THREAD

**Issue by JSomervilleFromAz** [Axway-API-Management-Plus/dynatrace-apim-oneagent#27]
General request to update docs or testing for this project for Java 11 and latest API GW version.

After upgrading, the error below was observed in the trace log by someone.
Replacing aspectjweaver-1.8.13.jar with aspectjweaver-1.9.6.jar solved that issue.

================================
ERROR  java exception running circuit:
java.lang.VerifyError: Expecting a stackmap frame at branch target 24 Exception Details:
Location:
com/vordel/dwe/http/ServerTransaction.sendResponse(ILjava/lang/String;Lcom/vordel/mime/HeaderSet;Lcom/vordel/mime/Body;I)V @0: aload_0
Reason:
Expected stackmap frame at this location.
[...]
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Unknown Source)

Thanks

**Comment by rathnapandi** [comment]
Hi @JSomervilleFromAz, 
Did the customer test in Aug 2023 release? 
Our readme document refers to aspectjweaver-1.9.6.jar as dependency.

**Comment by JSomervilleFromAz** [comment]
Hi @rathnapandi,

Yes the error was on Aug23, and yes that jar is what helped.  Sorry, I guess the readme was missed, (and the older jar was working pre upgrade for them).

Thanks

**Comment by rathnapandi** [comment]
Thanks for the confirmation @JSomervilleFromAz.
