### ISSUE TITLE
Does this support v7.7.20220228 and which branch to use?

### ISSUE THREAD

**Issue by venu124** [Axway-API-Management-Plus/dynatrace-apim-oneagent#28]
Hi there,

As the title says, I have below questions:

1. Does this support v7.7.**20220228** 
2. Also which branch to use? I assume Nov2021, correct?

Thanks in advance,
Venu

**Comment by rathnapandi** [comment]
Hi @venu124, 

Tested v7.7.20220228. Use the main branch. 

Thanks 
Rathna

**Comment by venu124** [comment]
Perfect. Thanks @rathnapandi :)

**Comment by venu124** [comment]
Hi @rathnapandi 

I see there are new oneagent[1] and aspectjweaver[2] jars available. Can we use these?

[1] oneagent-sdk-1.9.0.jar
(https://repo1.maven.org/maven2/com/dynatrace/oneagent/sdk/java/oneagent-sdk/1.9.0/oneagent-sdk-1.9.0.jar)

[2] aspectjweaver-1.9.9.jar
(https://repo1.maven.org/maven2/org/aspectj/aspectjweaver/1.9.9/aspectjweaver-1.9.9.jar)

**Comment by rathnapandi** [comment]
Sure, Its not been tested.   Do let me know if you run into any issues.

**Comment by venu124** [comment]
@rathnapandi 
We will start with 1.8.0 first and once confirm everything is working then we will try new version.

We also are installing gradle. Is this the version this project uses? **gradle-6.7**

Update: Oh wait, you are using a gradle wrapper. I don't need to install gradle then?

**Comment by rathnapandi** [comment]
Yes, it uses gradle version 6.7 and don't need to install, use gradlew command.

**Comment by venu124** [comment]
@rathnapandi
Thank you, yes I was able to run partially with gradlew command but it failed when I try to use Axway's embedded jre located at: apigateway/platform/jre.
I think I need to have a separate JDK installed to run this correct?

Also, do I need to generate dynatrace-aspectj-x.x.x.jar for each gateway installation OR can I reuse it across environments? (DEV,QA,PROD)

**Comment by rathnapandi** [comment]
Yes, you need a JDK to build the jar.  v7.7.20220228 uses JDK version  1.8.

Generate the jar once and use it on higher environment.

**Comment by venu124** [comment]
Build fails with attached error. [build_error.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/14056760/build_error.txt)

I'm trying this on RHEL 7 OS and OpenJDK-1.8.0.342.
Is this plugin supported for above OS and JDK combination?

**Comment by rathnapandi** [comment]
The project uses java. If we use the right jdk distribution, it should work.  Your error may be related to permission issue.  Change the gradle home location by using an option g

-g, --gradle-user-home
Specifies the Gradle User Home directory. The default is the .gradle directory in the user’s home directory.

**Comment by venu124** [comment]
Changed to a local location(/opt/gradle-axway) also I'm running as root but that did not help and I still see previous error. Doesn't look like permissions related.

In the trace, I also see below errors:
_file or directory '/opt/Axway-7.7.0/apigateway/lib', not found
file or directory '/opt/Axway-7.7.0/apigateway/lib/jce', not found
file or directory '/opt/Axway-7.7.0/apigateway/lib/plugins', not found_


I have set _apim_folder_  value as `/opt/Axway-7.7.0/apigateway`. Where should this point to exactly? _`*/apigateway/system/lib`_ ?

**Comment by rathnapandi** [comment]
It should be /opt/Axway-7.7.0/apigateway/system, I will update the readme.

**Comment by venu124** [comment]
It is successful this time but completed with 1 warning mentioned below, do we need to fix this before proceeding?

`/opt/dynatrace-apim-oneagent-main/build/classes/java/main!com/axway/aspects/apim/AxwayAspect.class [warning] advice defined in com.axway.aspects.apim.AxwayAspect has not been applied [Xlint:adviceDidNotMatch]`

Also another question:
Do I need to complete all the steps in setup instructions before running build? 
(creating _jvm.xml_, copying _oneagent-sdk-1.8.0.jar_, _aspectjweaver-1.9.6.jar_)

**Comment by venu124** [comment]
Hi @rathnapandi 

I went ahead and made the changes ignoring above warning.

My topology has 3 hosts(1 Admin Node Manager, 2 Gateways). Both gateways are independent meaning they don't share same code/APIs but linked to same ANM.

I made changes to one of the gateways and services seems to have started fine and I also see this in Gateway NM trace logs - "_Dynatrace SDK is active and capturing_"

But ANM is not able to reach the gateway which has the changes and reports it as offline in ANM traffic monitor dashboard. And in the ANM logs, I see the attached error related to RouterService.
[RouterService-errors-in-ANM.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/14086591/RouterService-errors-in-ANM.txt)


I just reverted the changes on the gateway and now ANM is reporting it as healthy and things are back to normal. I'm not sure what is happening here.
Does all the hosts in the topology(including ANM) needs to have these Dynatrace libs/changes for this work?

**Comment by rathnapandi** [comment]
Hi @venu124 , 

We don't need to setup dynatrace agent ANM, but it should not break functionality.  The trace does not have enough information to pinpoint the issue, can you share all stack trace?

**Comment by venu124** [comment]
@rathnapandi 
Here is the full trace 
[adminnodemanagermy-sandbox_log_20240129100240.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/14088655/adminnodemanagermy-sandbox_log_20240129100240.txt)

- anm-sandbox is ANM
- gateway1-sandbox is the gateway

I do see connection errors between these nodes in attached trace which are generally not present without these changes. Once I reverted connections errors disappeared.

Also you will find lot of "SSL protocol error" which is normal and exists with or without these changes. May be not related to current issue.

**Comment by ghost** [comment]
@venu124, 

Can you get the logs from the local node manager which is running along with gateway1-sandbox? as I do not see any references to dynatrace agent in the ANM log.

**Comment by venu124** [comment]
Here is the gateway1-sandbox NM log during the time period
[gateway1-sandbox_apigw_log_20240129093642.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/14089382/gateway1-sandbox_apigw_log_20240129093642.txt)

One thing I want to mention with regards to the APIM APIs in this gateway.
This gateway doesn't have any APIM APIs but just routes traffic to gateway2-sandbox which has APIM APIs, this is just a proxy gateway. Not sure if this makes any difference but just mentioning it.

**Comment by venu124** [comment]
Hi @rathnapandi 

Please let me know if you need more details. 
Thank you!

**Comment by rathnapandi** [comment]
Hi Venu, 

The plugin captures gateway polices and API Manger traffic.  You architecture should work. I am looking for log from apigatway/traces. You did share the logs of API gateway.

**Comment by venu124** [comment]
Thanks for your reply.
Okay, anything else can I do to troubleshoot this? like enabling DEBUG logs or something...

**Comment by marouanermidi** [comment]
Hello,

We are facing exactly the same problem, with Axway 7.7 February 2023 .

Do you have some news for this error ?

Thanks

**Comment by venu124** [comment]
No @marouanermidi.

@rathnapandi Did you get chance to look into this further?

Also let us know if we can troubleshoot and provide more logs.

**Comment by marouanermidi** [comment]
Hi @venu124 @rathnapandi ,

We resolved this by moving configuration from jvm.xml of the node into the API instance like this 
 /opt/axway/apigateway/conf/jvm.xml -> /opt/axway/apigateway/groups/group-x/instance-x/conf/jvm.xml

But we still think there is a problem with this jar, cause the old one works well in both places, @rathnapandi  if you can help us with this please?

**Comment by rathnapandi** [comment]
Hi @venu124 & @marouanermidi, 

The issue is happening while intercepting Node manager traffic.  will work and get back to you with more details / fix.

**Comment by marouanermidi** [comment]
Hi  @rathnapandi , 

Do you have an idea about the date of release of this fix please ?

Thanks

**Comment by marouanermidi** [comment]
Hi @rathnapandi @rathna-axway ,

Is there a workaround we can do before the fix please ?

Regards 
Marouane

**Comment by rathnapandi** [comment]
Hi @marouanermidi,

Sorry for the delay!!! The issue has been fixed. Can you please check out the latest code, build the jar file and test it?

The workaround is creating a jvm.xml file under /apigateway/groups/group-x/instance-x/conf/ which will avoid anm using dynatrace agent.

**Comment by marouanermidi** [comment]
Hi @rathnapandi,

Thanks for the fix, its working .

Regards
