### ISSUE TITLE
Metrics and UI

### ISSUE THREAD

**Issue by bruno-vc** [Axway-API-Management-Plus/dynatrace-apim-oneagent#4]
What information does it provide to Dynatrace? Is there any reports screenshot?

**Comment by mvenzke-axway** [comment]
You can see from the code what it grabs, like headers and API names, etc.:

https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/blob/main/src/main/java/com/axway/aspects/apim/AxwayAspect.java

This is the only image I could find of someone running it and I don't think it really shows you the transaction data:

![image](https://user-images.githubusercontent.com/60666497/190196746-b087dc16-f65a-4ea4-92ab-72ee68f7641b.png)
