### ISSUE TITLE
apim_folder lib paths incorrect?

### ISSUE THREAD

**Issue by jschutte27** [Axway-API-Management-Plus/dynatrace-apim-oneagent#5]
When setting apim_folder to the apigateway directly as instructed I had to update the build.gradle lib paths to include the system folder like this:

    implementation fileTree(dir: "${apim_folder}/system/lib", include: '*.jar')
    implementation fileTree(dir: "${apim_folder}/system/lib/plugins", include: '*.jar')

Is this the normal path?

**Comment by rathnapandi** [comment]
Yes @jschutte27 , i copied the jar files to local machine and used custom directory structure. 

Let me follow same naming convention as api gateway.
