### ISSUE TITLE
Problems on api manager 20230228

### ISSUE THREAD

**Issue by jschutte27** [Axway-API-Management-Plus/dynatrace-apim-oneagent#7]
I upgraded api manager from 20220530 to 20230228 and from dynatrace-aspectj-1.0.1.jar to dynatrace-aspectj-1.0.2.jar and now I am seeing this error in the gateway trace:

`
DEBUG | 3/31/23, 11:10:49.264 | Adding MessageListener: com.vordel.circuit.net.ConnectionProcessor$1@b2a1573
-- | -- | --
INFO | 3/31/23, 11:10:49.265 | Dynatrace  :: outgoing x-dynatrace header  FW4;-462096422;6;1834380753;184;0;-1871449397;1945;9f22;2h01;3h6d566dd1;4hb8;6h4a0b72fdbd2657ea40b2902bc1f7594b;7h4d10fe6eb31f70c6
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
FATAL | 3/31/23, 11:10:49.265 | [1695329e] can't set fieldname 'requestHeader': must be done before node is being started.
DEBUG | 3/31/23, 11:10:49.265 | Get connection to host devapi.example.com port 443 scheme https
`

It also appears not to create services for each API in api manager like it did before.  This happened with 20230228 on both versions of dynatrace-aspectj-1.0.x.jar.  Now all the traffic in dynatrace shows under the "Requests executed in background threads of vshell" service which isn't very nice to look at compare to before.

**Comment by jschutte27** [comment]
Hi @rathnapandi 

Is this something you will be able to look into?  If you need more info or want me to test anything let me know.  Here are a couple screenshots from dyantrace:

The old version creates services for each API in api manager:
![image](https://user-images.githubusercontent.com/58127265/230907285-c396a14c-c7a1-4909-ab1c-5893a0901f10.png)

The new one only creates services for built in API manager API's:
![image](https://user-images.githubusercontent.com/58127265/230907375-f7277ca8-be79-4d66-ba0d-ebbce344c9ee.png)
All the API traffic shows under "Requests executed in background threads of vshell"

Thanks,
Jeremiah

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

There is a java api change on Feb 2023 release. Can you test with 
[dynatrace-aspectj-1.0.3.jar.zip](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/11192473/dynatrace-aspectj-1.0.3.jar.zip)

unzip dynatrace-aspectj-1.0.3.jar.zip and copy the jar file to API Gateway.

**Comment by jschutte27** [comment]
Hi @rathnapandi,

I tried the supplied jar file and it caused all requests to error 500 on the gateway.  Here is a trace from the healthcheck endpoint:

[70c83564f20093c96a0020ad.txt](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/11204884/70c83564f20093c96a0020ad.txt)

Is there anything else I can provide to troubleshoot?

Thanks,
Jeremiah

**Comment by rathnapandi** [comment]
Hi @jschutte27, 
Can you add a host http header and test it?   or use the attached jar file. 
[dynatrace-aspectj-1.0.3-hostheaderfix.jar.zip](https://github.com/Axway-API-Management-Plus/dynatrace-apim-oneagent/files/11204950/dynatrace-aspectj-1.0.3-hostheaderfix.jar.zip)

**Comment by jschutte27** [comment]
This jar file looks like it fixed the issues.  Thanks for your help @rathnapandi!

**Comment by rathnapandi** [comment]
@jschutte27  Thanks for the confirmation.
